version: '2'

services:
  web:
    image: nginx:latest
    hostname: selfservicepassword.example.com
    volumes_from:
      - php
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: moss/self-service-password
    hostname: selfservicepassword.example.com
    environment:
      LDAP_SERVER: "ldap://openldap.example.com"
      LDAP_STARTTLS: 'false'
      LDAP_BINDDN: "cn=admin,dc=example,dc=com"
      LDAP_BINDPASS: "supersecurepassword"
      LDAP_BASE_SEARCH: "ou=people,dc=example,dc=com"
      LDAP_LOGIN_ATTRIBUTE: "uid"
      LDAP_FULLNAME_ATTRIBUTE: "cn"
      ADMODE: 'false'
      AD_OPT_FORCE_UNLOCK: 'false'
      AD_OPT_FORCE_PWD_CHANGE: 'false'
      AD_OPT_CHANGE_EXPIRED_PASSWORD: 'false'
      SAMBA_MODE: 'false'
      SHADOW_OPT_UPDATE_SHADOWLASTCHANGE: 'false'
      PASSWORD_HASH: 'auto'
      PASSWORD_MIN_LENGTH: 0
      PASSWORD_MAX_LENGTH: 0
      PASSWORD_MIN_LOWERCASE: 0
      PASSWORD_MIN_UPPERCASE: 0
      PASSWORD_MIN_DIGIT: 0
      PASSWORD_MIN_SPECIAL: 0
      PASSWORD_NO_REUSE: 'true'
      PASSWORD_SHOW_POLICY: 'false'
      PASSWORD_SHOW_POLICY_POSITION: "above"
      WHO_CAN_CHANGE_PASSWORD: "user"
      QUESTIONS_ENABLED: 'false'
      LDAP_MAIL_ATTRIBUTE: "mail"
      MAIL_FROM: "noreply@example.com"
      MAIL_FROM_NAME: "Password Admin"
      NOTIFY_ON_CHANGE: 'true'
      SMTP_DEBUG: 0
      SMTP_HOST: "smtp.example.com"
      SMTP_AUTH_ON: 'true'
      SMTP_USER: "noreply@example.com"
      SMTP_PASS: "smtppassword"
      SMTP_PORT: 587
      SMTP_SECURE_TYPE: "tls"
      USE_SMS: 'false'
      IS_BEHIND_PROXY: 'false'
      SHOW_HELP: 'true'
      DEBUG_MODE: 'false'
      SECRETEKEY: 'secretkey'
      USE_RECAPTCHA: 'false'
      RECAPTCHA_PUB_KEY: 'akjsdnkajnd'
      RECAPTCHA_PRIV_KEY: 'aksdjnakjdnsa'
      DEFAULT_ACTION: "change"
